// Generated by LiveScript 1.5.0
(function(){
  'use strict';
  var util, google, shorten;
  util = require('util');
  google = require('googleapis');
  shorten = require('goo.gl');
  module.exports = function(){
    var this$ = this;
    return this.register_special_command({
      name: 'g',
      description: 'Perform a web search using Google.',
      admin_only: false,
      fn: function(event, input_data, output_data){
        var opts, query;
        if (!input_data.args) {
          this$.send('notice', event.person.nick, 'I can\'t search for nothing, silly!');
          return;
        }
        opts = this$.botOptions.pluginOptions['irc-support-bot-search'];
        query = input_data.args + ' -site:w3schools.com -site:tizag.com';
        return function(_){
          var full;
          full = "https://google.com/search?q=" + query;
          return shorten(full, opts.apiKey, function(err, result){
            var short;
            if (!err) {
              short = result.id;
            }
            return _(short || full);
          });
        }(function(moreResultsUrl){
          if (!opts) {
            console.error('No options specified for « irc-support-bot-search ». Missing API key.');
            return;
          }
          return google.customsearch('v1').cse.list({
            auth: opts.apiKey,
            cx: opts.engineId,
            q: query
          }, function(err, result){
            var message;
            if (err) {
              message = 'Oops, something went wrong!';
            } else if (!result.items[0]) {
              message = "No results for query '" + input_data.args + "'";
            } else {
              message = "Google says \"" + result.items[0].title + "\" • " + result.items[0].link + " • More results: " + moreResultsUrl;
            }
            return this$.send(output_data.method, output_data.recipient, message);
          });
        });
      }
    });
  };
}).call(this);
